#
# Module manifest for module 'PSColorizer2'
#
# Generated by: chipgraphics
#
# Generated on: 12.24.2023
#
# Updated on: 12.24.2023
#

@{
  RootModule        = 'PSColorizer2.psm1'

  ModuleVersion     = '2.0.0'

  GUID              = '0b1494ff-1050-4777-8ebb-3b069eaeacab'

  Author            = 'chipgraphics'

  CompanyName       = 'None'

  Copyright         = '(c) 2020-2021 chipgraphics. Distributed under the MIT license terms.'

  Description       = 'Outputs color-formatted messages to console.'

  PowerShellVersion = '5.1'

  FunctionsToExport = @(
    'Write-Colorized2',
    'Write-Message',
    'Set-ConsoleBColor',
    'Set-ConsoleColor'
  )

  AliasesToExport   = 'wc2', 'colorize2'

  PrivateData       = @{

    PSData = @{

      LicenseUri = 'https://github.com/chipgraphics/PSColorizer2/blob/master/LICENSE'

      ProjectUri = 'https://github.com/chipgraphics/PSColorizer2'

      IconUri    = 'https://github.com/chipgraphics/PSColorizer2/blob/master/logo.png'

    }

  }
  HelpInfoURI       = 'https://github.com/chipgraphics/PSColorizer2#readme'
}
