#
# Module manifest for module 'PSColorizer'
#
# Generated by: 2CHEVSKII
#
# Generated on: 07.04.2020
#

@{
    RootModule        = 'PSColorizer.psm1'

    ModuleVersion     = '1.0.0'

    GUID              = 'f1cdadff-6d3e-4ae8-bfe6-98b7717a72c2'

    Author            = '2CHEVSKII'

    CompanyName       = 'Unknown'

    Copyright         = '© 2020 2CHEVSKII. Distributed under the MIT license terms.'

    Description       = 'Outputs color-formatted messages to console.'

    PowerShellVersion = '5.1'

    FunctionsToExport = 'Write-Colorized'

    CmdletsToExport   = 'Write-Colorized'

    AliasesToExport   = 'wc', 'colorize'

    PrivateData       = @{

        PSData = @{

            LicenseUri = 'https://github.com/2chevskii/PSColorizer/blob/master/LICENSE'

            ProjectUri = 'https://github.com/2chevskii/PSColorizer'

            IconUri    = 'https://github.com/2chevskii/PSColorizer/blob/master/logo.png'

        }

    }
    HelpInfoURI       = 'https://github.com/2chevskii/PSColorizer#readme'
}

